// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcMr9ZIgoKbFFOnB1WbcHkWiHOs3bk6r0',
    appId: '1:948167988626:web:7e9f5216c505ba25c39d4b',
    messagingSenderId: '948167988626',
    projectId: 'expensesplitterapp-9331f',
    authDomain: 'expensesplitterapp-9331f.firebaseapp.com',
    storageBucket: 'expensesplitterapp-9331f.firebasestorage.app',
    measurementId: 'G-482RG0XJQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5qfjUXNvKKBOlmLS73ixwef8JAIu6AZI',
    appId: '1:948167988626:android:d0e88bf62e540c66c39d4b',
    messagingSenderId: '948167988626',
    projectId: 'expensesplitterapp-9331f',
    storageBucket: 'expensesplitterapp-9331f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2yKH8KKTIeNO9S4MjOAiTyxbOMW7JLFA',
    appId: '1:948167988626:ios:bc7d84a7723f2e62c39d4b',
    messagingSenderId: '948167988626',
    projectId: 'expensesplitterapp-9331f',
    storageBucket: 'expensesplitterapp-9331f.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2yKH8KKTIeNO9S4MjOAiTyxbOMW7JLFA',
    appId: '1:948167988626:ios:bc7d84a7723f2e62c39d4b',
    messagingSenderId: '948167988626',
    projectId: 'expensesplitterapp-9331f',
    storageBucket: 'expensesplitterapp-9331f.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcMr9ZIgoKbFFOnB1WbcHkWiHOs3bk6r0',
    appId: '1:948167988626:web:3649546c1ff00e7ec39d4b',
    messagingSenderId: '948167988626',
    projectId: 'expensesplitterapp-9331f',
    authDomain: 'expensesplitterapp-9331f.firebaseapp.com',
    storageBucket: 'expensesplitterapp-9331f.firebasestorage.app',
    measurementId: 'G-G4EP4D7QVS',
  );
}
